[build-system]
requires = ["setuptools", "wheel", "pybind11==2.6.0"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[[tool.mypy.overrides]]
module = ["pylops", "curvelops.fdct2d_wrapper", "curvelops.fdct3d_wrapper"]
ignore_missing_imports = true
