# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.22.dev0+gd1aeee6.d20230115'
__version_tuple__ = version_tuple = (0, 22, 'dev0', 'gd1aeee6.d20230115')
